default:
	@echo "install               copy kmodtemplate to /bin"
	@echo "clean                 clean all kmod-* in pwd"

install:
	chmod +x kmodtemplate
	cp -a kmodtemplate /bin/

clean:
	rm -rf kmod-*
