/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * Lua based LSM
 *
 * Copyright (C) 2025 The Alibaba Cloud Linux Authors.
 */

#include "debug.h"
#include <linux/signal.h>
#include "lsm.h"
#include "auxlib.h"

static const struct const_value signals[] = {
	CONST_DEFINE(SIGHUP),
	CONST_DEFINE(SIGINT),
	CONST_DEFINE(SIGQUIT),
	CONST_DEFINE(SIGILL),
	CONST_DEFINE(SIGTRAP),
	CONST_DEFINE(SIGABRT),
	CONST_DEFINE(SIGIOT),
	CONST_DEFINE(SIGBUS),
	CONST_DEFINE(SIGFPE),
	CONST_DEFINE(SIGKILL),
	CONST_DEFINE(SIGUSR1),
	CONST_DEFINE(SIGSEGV),
	CONST_DEFINE(SIGUSR2),
	CONST_DEFINE(SIGPIPE),
	CONST_DEFINE(SIGALRM),
	CONST_DEFINE(SIGTERM),
	CONST_DEFINE(SIGSTKFLT),
	CONST_DEFINE(SIGCHLD),
	CONST_DEFINE(SIGCONT),
	CONST_DEFINE(SIGSTOP),
	CONST_DEFINE(SIGTSTP),
	CONST_DEFINE(SIGTTIN),
	CONST_DEFINE(SIGTTOU),
	CONST_DEFINE(SIGURG),
	CONST_DEFINE(SIGXCPU),
	CONST_DEFINE(SIGXFSZ),
	CONST_DEFINE(SIGVTALRM),
	CONST_DEFINE(SIGPROF),
	CONST_DEFINE(SIGWINCH),
	CONST_DEFINE(SIGIO),
	CONST_DEFINE(SIGPOLL),
	CONST_DEFINE(SIGPWR),
	CONST_DEFINE(SIGSYS),
	{ NULL }
};

int luaopen_signal(lua_State *L)
{
	lua_newtable(L);
	setconst(L, signals);
	return 1;
}
